theme: jekyll-theme-cayman
title: Welcome to Alireza's homepage!
description: I am a junior computer scientist and I have tried to showcase some of my projects on this website.
![Image](https://lab.getapp.com/wp-content/uploads/2019/09/HEAD_-_Citizen_data_scientist_vs_expert_data_scientist-_What_27s_the_difference_-_Blog_-_1200x655.png)
