theme: jekyll-theme-cayman
title: Welcome to Alireza's homepage!
description: I am a junior computer scientist with demonstrated leadership skills and entrepreneurial spirit, thus, able to give expression to ideas, solve problems and make it work.
![Image](C:\Users\shiraz computer\Desktop\study permit2020)
